### ISSUE TITLE
[hotfix] 크래시 대응 이슈

### ISSUE THREAD

**Issue by SsongSik** [MYONGSIK/Android#45]

**Comment by KwakEuiJin** [comment]
재현 경로: 오늘의 학식 화면에서 교직원, 생활관, 학관 식당 중 아무거나 클릭 후 명진당 진입시 크래시 발생
크래시 종류: Index size Exception

원인 찾았습니다. 현재 HomeFragment에서 LiveData를 구독할 때 LiveData는 이전 데이터 값을 가지고 있습니다 
(activity의 뷰모델이기 때문에 activity가 죽지 않는 이상 데이터는 계속 살아있습니다.)
-> 즉 현재 Flow가 교직원, 생활관, 학관의 경우  중식, 석식 2가지에 대한 총 10개의 리스트를 가지고 있지만, 명진당의 경우 15개를 가지고 있어야 하기 때문에 남아있던 라이브데이터(10)의 리스트를 리사이클러뷰를 렌더링 하는 과정에서 에러가 났습니다. 

이 부분 현재는 if문으로 분기처리하지만 fragment의 ViewModel로 변경하거나 Nullable 처리를 통해서 해결하는 방안을 구상하는 것이 좋을 것 같습니다.

**Comment by KwakEuiJin** [comment]
성식님 main에 바로 푸시해도 괜찮을까요? 일단은 if문 하나로 처리가 가능해서요!
핫픽스 배포 빠르게 부탁드립니다~!!
다음 릴리즈에 리팩터링 진행해서 나가면 될 것 같습니다.

**Comment by KwakEuiJin** [comment]
main에 푸시 완료했습니다. 이 문제를 근본적으로 해결하기 위해서는 ViewHolder 및 LiveData의 구독 방식의 변경이 필요할 것으로 보입니다.

**Comment by SsongSik** [comment]
네네! 기능별로 ViewModel을 나누어서 프래그먼트별로 변경하는 것도 좋을 것 같습니다! 이대로 핫픽스 나가겠습니다!
