### ISSUE TITLE
[infra] Firebase 연동

### ISSUE THREAD

**Issue by SsongSik** [MYONGSIK/Android#46]

**Comment by KwakEuiJin** [comment]
일단 크래시 추적 기능만 우선적으로 넣어보고 운영시간 같은건 RemoteConfig로 변경성을 두는 것도 좋을 것 같습니다!!

혹시 성식님께서 파베 계정 만드시면 권한 초대만 해주시면 SDK 다운받아서 기능 추가 해놓도록 하겠습니다~!!

**Comment by KwakEuiJin** [comment]
파베 추가 PR이 올라갔기에 이슈를 종료합니다.
