### ISSUE TITLE
[feat] refresh layout 추가 및 스크롤 설정

### ISSUE THREAD

**Issue by SsongSik** [MYONGSIK/Android#57]
## 이슈사항
1. iOS와 통일성을 갖추기 위해 refresh 를 추가한다.
2. 전체스크롤이 되게끔 변경한다.

**Comment by KwakEuiJin** [comment]
성식님 이거 전체스크롤이 안되네요 Nested ScrollView로 감쌌는데 적용이 안되네요 하핳하

**Comment by SsongSik** [comment]
ㅋㅋㅋㅋㅋㅋㅋ그럼 일단 리프레시부터 적용할까요??

**Comment by KwakEuiJin** [comment]
일단은 추가 해도 좋을 것 같습니다 PR올리겠습니다!

**Comment by KwakEuiJin** [comment]
일단 페이징을 쓰는게 무언가 영향을 끼치는가에 대해 고민하고 있고 무엇보다도 제가 에뮬로만 테스트해봐서 정확하지 않을 수 있어요

**Comment by SsongSik** [comment]
지금 식당 랭킹 보여지는 곳에서는 아마 페이징을 안쓰고 있습니다! 저도 한 번 테스트를 진행해볼게요 :)

**Comment by SsongSik** [comment]
확인해봤는데.. 이거 그냥 리사이클러뷰에 헤더를 추가하는 방식으로 가야할까요?

**Comment by SsongSik** [comment]
의진님! 제가 리사이클러뷰 헤더 추가해서 이슈해결중입니다!

**Comment by SsongSik** [comment]
PR올렸으므로 이슈닫음
