### ISSUE TITLE
[feat] 리뷰에 식당 이름 추가하기

### ISSUE THREAD

**Issue by SsongSik** [MYONGSIK/Android#62]
## 이슈사항
- 리뷰테이블에 식당이름 추가되었음. request로 식당이름 하나 던져주기

**Comment by SsongSik** [comment]
MCC식당, 교직원식당, 생활관식당, 학생식당, 명진당식당 이렇게 5개 중에 하나 request로 넘겨주면 됩니당

**Comment by KwakEuiJin** [comment]
해당 작업 제가 진행하겠습니다.
