### ISSUE TITLE
[fix] 2.2.6 크래시대응

### ISSUE THREAD

**Issue by SsongSik** [MYONGSIK/Android#70]
## 이슈사항
- connectException 처리
- 낮은 OS에서의 검색

다음 2.2.7버전에서 대응해서 나가야 할 것 같습니다.
Firebase 크래시 확인해주세용

**Comment by KwakEuiJin** [comment]
넵넵 코루틴쪽에 에러 핸들링 추가하고 레트로핏 예외처리 찾아서 구현해놓겠습니다.
