### ISSUE TITLE
android.system.ErrnoException - isConnected failed: ECONNABORTED 

### ISSUE THREAD

**Issue by KwakEuiJin** [MYONGSIK/Android#71]
[크래시 링크](https://console.firebase.google.com/u/0/project/myongsik-1667d/crashlytics/app/android:com.myongsik.myongsikandroid/issues/0020144daaab949ce317cb804c705872?hl=ko&time=last-seven-days&sessionEventKey=6423F3B6014D00016CCBDFE50FCF5712_1794324670803671296)

# 크래시 발생
해당 크래시는 서버와의 통신시에 발생하는 에러로 추정됩니다. 코루틴내에 exceptionHandler를 추가해서 예외처리 해야할 것 같네요

**Comment by SsongSik** [comment]
이 부분 Base에 작성해서 공통으로 사용하는게 좋을 것 같아요
