### ISSUE TITLE
[fix] 가게 거리 가려지는 이슈

### ISSUE THREAD

**Issue by KwakEuiJin** [MYONGSIK/Android#72]
가게 상호명이 길면 거리가 얼마나 남았는지 보이지 않는 이슈가 있습니다.

**Comment by KwakEuiJin** [comment]
![image](https://user-images.githubusercontent.com/93872496/229095747-647fe40e-1304-4c1f-af4f-9004934a0661.png)

**Comment by KwakEuiJin** [comment]
글자 크기를 sp로 두어서 발생한 이슈로 파악됩니다. 앞으로의 textSize 컨벤션을 sp로 갈까요? dp로 갈까요??

**Comment by SsongSik** [comment]
흠..해상도가 낮은 기기에서 저런 이슈가 발생하는거죠!? dp 하면 ptsd오는데........흠 고민을 좀 해봐야 할 것 같습니다.
만일 바꾼다고 해도 기존에 있던 것을 다 바꿔야하는것인지 고민이 되네요

**Comment by SsongSik** [comment]
의진님 생각은 어떠세요?

**Comment by KwakEuiJin** [comment]
음... 확인해보니 해상도 때문은 아닌 것 같습니다. 시스템상의 글자크기 때문인 것 같은데요, 사용자의 접근성을 위해서 sp를 도입하는게 맞을 것 같습니다. 하지만 결국 거리가 가려지게 되면 기능상의 문제가 생긴다고도 판단되긴 합니다. 이 부분은 sp로 가져가고 Known Issue로 처리할까요?

**Comment by SsongSik** [comment]
네넵 그게 좋을 것 같아요. 대신 현재 식당의 이름이 몇글자 이상 넘어갔을 때 ...으로 표시되고 있는지 파악하고 그것을 조금 더 제한을 두는 것이 좋을 것 같네요!
